plugin-dir: plugins

# config for data / data-source

data:
  view-dir: view

data-source-parsers:
  - suffix: .json
    provider: builtin://JsonAdapter
  - suffix: .yaml
    provider: builtin://YamlAdapter
    config:
      extname: yaml
  - suffix: .yml
    config:
      provider: builtin://YamlAdapter
      extname: yml
  - suffix: .csv
      provider: builtin://CsvAdapter
  - suffix: .restapi
    provider: plugin://::WebootPlugin::Parser::RestApiParser

data-source:
  - file://./data

# config for action hook

hooks:
  nop:
    provider: builtin://NopHook
    config:
      hello: world
  feed: plugin://::WebootPlugin::Generator::FeedGenerator

# config for filters / pipelines

filters:
  nop: builtin://NopFilter
  layered:
    provider: builtin://LayeredFilter
    config:
      layouts-dir: ${data.view-dir}
  markdown_to_html:
    provider: builtin://MarkdownToHtmlFilter
    config:
      code-highlighter: rouge
  scss: plugin://::WebootPlugin::Filter::ScssFilter

pipelines:
  - name: example # 可在 scope 里引用 pipeline: <key> 为其单独指定一个处理器
    suffix: .example
    filters:
      - name: nop
        config:
          hello: world
      - nop
    pre-hooks:
      - name: nop
        config:
          hello: world
    post-hooks:
      - nop
  - suffix: .htm .html
    filters:
      - layered
  - name: md
    suffix: .md
    filters:
      - markdown_to_html
      - layered
  - suffix: .scss
    filters:
      - scss

# config for generating

source-dir: src
target-dir: out

default-page-config:
  weboot: WEBOOT

generating:
  pre-hooks:
    - nop
  post-hooks:
    - name: feed
      config:
        type: atom
        fullpath: /atom.xml

# config for preview / deployment

server:
  local:
    host: 127.0.0.1
    port: 4000
    root: ""
  remote:
    host: weboot.lan
    port: 80
    root: ""
