# =============================
# site config of weboot project
# =============================

# config for plugin

plugin-dir: plugins

# about datasource

datasource-config:
  file:
    provider: DataSource::FileDataSource
    config:
      dir: data
      readers:
        - suffix: .json
          provider: Reader::JsonReader
        - suffix: .yaml
          provider: Reader::YamlReader
          config:
            extname: yaml
        - suffix: .yml
          provider: Reader::YamlReader
          config:
            extname: yml
        - suffix: .csv
          provider: Reader::CsvReader
  random:
    provider: DataSource::RandomDataSource
    config:
      seed: 0

primary-datasource: file

# about rendering

filters:
  nop: Filter::NopFilter
  layered:
    provider: Filter::LayeredFilter
    config:
      layouts-dir: view
  markdown_to_html:
    provider: Filter::MarkdownToHtmlFilter
    config:
      code-highlighter: rouge
  scss: Plugin::Filter::ScssFilter

pipelines:
  - name: example
    suffix: .example
    filters:
      - name: nop
        config:
          hooks:
            - name: nop
              config:
                weboot: WEBOOT
            - nop
      - nop
  - suffix: .htm .html
    filters:
      - layered
  - name: md
    suffix: .md
    filters:
      - markdown_to_html
      - layered
  - suffix: .scss
    filters:
      - scss

source-dir: src
target-dir: out

default-page-config:
  weboot: WEBOOT

# about hooks

hooks:
  nop:
    provider: Hook::NopHook
    config:
      weboot: WEBOOT
  feed: Plugin::Generator::FeedGenerator

after-scanning:
  - nop

after-rendering:
  - name: feed
    config:
      type: atom
      fullpath: /atom.xml

after-writing:
  - nop

# about preview & deployment

server:
  local:
    host: 127.0.0.1
    port: 4000
    root: ""
  remote:
    host: weboot.lan
    port: 80
    root: ""
