# =============================
# site config of weboot project
# =============================

# config for plugin

plugin-dir: plugins

# config for data / datasource

datasource-config:
  file:
    provider: builtin://FileDatasource
    config:
      dir: data
      readers:
        - suffix: .json
          provider: builtin://Stream::JsonReader
        - suffix: .yaml
          provider: builtin://Stream::YamlReader
          config:
            extname: yaml
        - suffix: .yml
          config:
            provider: builtin://Stream::YamlAdapter
            extname: yml
        - suffix: .csv
            provider: builtin://Stream::CsvAdapter
  random:
    provider: builtin://RandomDatasource
    config:
      seed: 0

primary-datasource: file

# config for action hook

hooks:
  nop:
    provider: builtin://NopHook
    config:
      hello: world
  feed: plugin://::WebootPlugin::Generator::FeedGenerator

# config for filters / pipelines

filters:
  nop: builtin://NopFilter
  layered:
    provider: builtin://LayeredFilter
    config:
      layouts-dir: view
  markdown_to_html:
    provider: builtin://MarkdownToHtmlFilter
    config:
      code-highlighter: rouge
  scss: plugin://::WebootPlugin::Filter::ScssFilter

pipelines:
  - name: example # 可在 scope 里引用 pipeline: <key> 为其单独指定一个处理器
    suffix: .example
    filters:
      - name: nop
        config:
          weboot: WEBOOT
      - nop
    pre-hooks:
      - name: nop
        config:
          weboot: WEBOOT
    post-hooks:
      - nop
  - suffix: .htm .html
    filters:
      - layered
  - name: md
    suffix: .md
    filters:
      - markdown_to_html
      - layered
  - suffix: .scss
    filters:
      - scss

# config for rendering

source-dir: src
target-dir: out

default-page-config:
  weboot: WEBOOT

rendering:
  pre-hooks:
    - nop
  post-hooks:
    - name: feed
      config:
        type: atom
        fullpath: /atom.xml

# config for preview / deployment

server:
  local:
    host: 127.0.0.1
    port: 4000
    root: ""
  remote:
    host: weboot.lan
    port: 80
    root: ""
