data:
  data-dir: db
  file-root-dir: src
  view-root-dir: view
  output-root-dir: dist

data-parsers:
  - suffix: .yaml
    filters:
      - parser: YamlParser
        config:
  - suffix: .json
    filters:
      - parser: JsonParser
        config:

filters:
  LayeredFilter:
    alias: layered
    config:
      layouts-dir: ${view-root-dir}
  MarkdownToHtmlFilter:
    config:
      code-highlighter: rouge
  ScssFilter:
    config:

hooks:
  FeedGenerator:
    alias: feed
    config:
      path: /atom.xml

pipeline:
  - name: example # 可在 scope 里引用 pipeline: <key> 为其单独指定一个处理器
    suffix: .example
    filters:
      - name: NopFilter
        config:
        pre-hooks:
          - name: NopHook
            config:
              hello: world
        post-hooks:
          - nop
      - nop
  - suffix: .htm .html
    filters:
      - layered
  - name: md
    suffix: .md
    filters:
      - MarkdownToHtmlFilter
      - layered
  - suffix: .scss
    filters:
      - ScssFilter

before-all:
  - nop
after-all:
  - nop
  - name: feed
    config:

server:
  local:
    host: 127.0.0.1
    port: 4000
    root: ""
  remote:
    host: weboot.lan
    port: 80
    root: ""
